### ISSUE TITLE
Loading mesh model

### ISSUE THREAD

**Issue by amichlee** [chai3d/chai3d#6]
I get this issue non-deterministically on Linux only when I load obj models. Happens perhaps 1/100 times for the same obj model. 

Program received signal SIGSEGV, Segmentation fault.
0x00000000004f1894 in chai3d::cOBJModel::parseFaceString(char*, chai3d::cFace*, chai3d::cVector3d const*, chai3d::cVector3d const*, chai3d::cVector3d const*, unsigned int) ()
(gdb) bt
#0  0x00000000004f1894 in chai3d::cOBJModel::parseFaceString(char*, chai3d::cFace*, chai3d::cVector3d const*, chai3d::cVector3d const*, chai3d::cVector3d const*, unsigned int) ()
#1  0x00000000004f7343 in chai3d::cOBJModel::LoadModel(char const*) ()
#2  0x00000000004f77bb in chai3d::cLoadFileOBJ(chai3d::cMultiMesh*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()

**Comment by amichlee** [comment]
Turns out it's really easy to create corrupted stl files from Solidworks and OnShare (and the resulting obj files will be corrupted). What I did was to delete the faces that were corrupted (they were in a different shade in blender). Since when you create a mesh model, you create a convex hull, so missing faces should not affect this too much.
